import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // Generic Styles
  container: {
    flex: 1,
    padding: 0,
    margin: 0,
  },
  textInput: {
    fontSize: 14,
    fontFamily: 'System',
    color: '#707070',
  },
  heading: {
    fontFamily: 'System',
    marginBottom: 15,
  },
  link: {
    textDecorationLine: 'none',
    color: '#0075A3',
  },
  paragraph: {
    marginBottom: 15,
  },
  underlineLink: {
    textDecorationLine: 'underline',
  },
  img: {
    maxWidth: '100%',
    height: 'auto',
  },
  button: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: '#fff',
    borderRadius: 5,
    fontFamily: 'System',
    cursor: 'pointer',
  },
  // Viewpoint Styles
  viewpoint: {
    width: '100%',
    maxWidth: 1260,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leftContainer: {
    width: '35%',
    padding: 60,
    backgroundColor: 'rgba(255,255,255,0.75)',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    minHeight: 550,
    backdropFilter: 'blur(6px)',
  },
  viewpointLogo: {
    maxWidth: 252,
    marginBottom: 30,
  },
  leftContainerHeading: {
    textTransform: 'uppercase',
    color: '#0075A3',
    fontWeight: '700',
    fontSize: 32,
    marginBottom: 15,
  },
  leftContainerButton: {
    display: 'flex',
    flexDirection: 'row',
    width: 200,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1C9DE3',
    borderRadius: 4,
    cursor: 'pointer',
    marginBottom: 15,
  },
  rightContainer: {
    width: '65%',
    backgroundColor: 'rgba(0,117,163,0.75)',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '80px 55px',
    backdropFilter: 'blur(6px)',
    color: '#fff',
  },
  verificationAreaHeading: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 28,
  },
  formRow: {
    marginBottom: 24,
  },
  label: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  infoBox: {
    fontSize: 11,
    marginTop: 7,
  },
  verificationAreaButton: {
    display: 'flex',
    flexDirection: 'row',
    width: 200,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#fff',
  },
  reactDatepickerWrapper: {
    width: '100%',
  },
  input: {
    width: '100%',
  },
  questionBoxHeading: {
    fontSize: 32,
    fontWeight: '700',
    marginBottom: 4,
  },
  readMore: {
    fontSize: 14,
    fontWeight: '400',
    marginBottom: 18,
  },
  readMoreLink: {
    color: '#fff',
  },
  captionBox: {
    fontSize: 14,
    marginBottom: 20,
    maxWidth: 564,
  },
  voteBoxHeading: {
    fontSize: 16,
    marginBottom: 8,
  },
  questionLabel: {
    backgroundColor: '#fff',
    color: '#5A5A5A',
    fontWeight: '700',
    position: 'relative',
    marginBottom: 8,
    padding: '15px 28px',
    cursor: 'pointer',
    fontSize: 18,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#bbb',
  },
  check: {
    position: 'absolute',
    right: 25,
    top: 10,
    width: 36,
    height: 36,
    borderWidth: 1,
    borderColor: '#ACACAC',
    borderRadius: 5,
    lineHeight: 30,
    textAlign: 'center',
  },
  checkImg: {
    verticalAlign: 'middle',
  },
  buttonPanel: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingTop: 30,
  },
  buttonPanelButton: {
    display: 'flex',
    flexDirection: 'row',
    width: 200,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#fff',
    fontWeight: '400',
    fontSize: 14,
  },
  btnCancel: {
    fontSize: 14,
    fontWeight: '700',
    marginRight: 35,
    textDecorationLine: 'underline',
    cursor: 'pointer',
  },
  ebConfirmationBox: {
    borderRadius: 5,
    backgroundColor: 'rgba(255,255,255,0.75)',
    backdropFilter: 'blur(4px)',
    width: '100%',
    maxWidth: 625,
  },
  ebHeader: {
    margin: 0,
    padding: '18px 53px',
    borderBottomWidth: 1,
    borderBottomColor: '#ADADAD',
    display: 'flex',
    alignItems: 'center',
  },
  ebHeaderHeading: {
    color: '#1D9FE4',
    fontSize: 32,
    width: '100%',
    margin: 0,
  },
  ebHeaderCancel: {
    cursor: 'pointer',
    opacity: 0.5,
  },
  ebDataboxy: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    minHeight: 190,
    padding: '20px 53px',
  },
  ebQuestion: {
    fontSize: 26,
    fontWeight: '700',
    color: '#6E6E6E',
    marginBottom: 15,
  },
  ebVoteBox: {
    display: 'flex',
    color: '#727272',
    fontSize: 26,
    lineHeight: 26,
  },
  ebCheck: {
    width: 32,
    height: 32,
    borderWidth: 1,
    borderColor: '#C3C3C3',
    padding: 4,
    borderRadius: 5,
    marginRight: 18,
    lineHeight: 0,
  },
  ebButtonPanel: {
    paddingRight: 55,
    paddingTop: 0,
    paddingBottom: 55,
  },
  ebButtonPanelButton: {
    backgroundColor: '#1D9FE4',
    borderColor: '#1D9FE4',
  },
  ebThankyou: {
    width: '100%',
    maxWidth: 930,
    backgroundColor: 'rgba(255,255,255,0.75)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 480,
    borderRadius: 10,
  },
  ebThankyouImg: {
    marginBottom: 30,
  },
  ebThankyouHeading: {
    color: '#000',
    fontSize: 34,
  },
  ebThankyouParagraph: {
    color: '#6D6D6D',
    marginBottom: 0,
    fontSize: 14,
  },
  ebExpiretime: {
    margin: 0,
    fontWeight: '700',
    fontSize: 26,
    color: '#6E6E6E',
  },
  ebExpiretimeSpan: {
    color: '#FF0000',
  },
});

export default styles;
